name: Documentation

on:
  push:
    branches: [ master ]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - name: Build docs
        run: |
          cd docs
          npx -p typescript -p typedoc typedoc
          mv generated ..
      - name: Commit docs
        run: |
          git fetch origin docs
          git checkout docs --
          rm -rf docs
          mv generated docs
          git add docs
          git config user.name pavulon
          git config user.email pavulon@users.noreply.github.com
          git commit -m 'Update docs'
          git push
